### PR TITLE
Fix the parsing and evaluation of the Accepts Header

### LINKED ISSUE #225: Detected MIME/format changed from 0.9 to 1.0
During migration to Hanami 1.0 (from 0.9), I've noticed that now my `json` actions require to specify `self.format = :json` or response will be returned as `html` otherwise.

Accordingly to gitter chat with @jodosha , it seems that bug could be introduced in #206 or #191

### PR DESCRIPTION
**Pull request by mereghost**
# Accept Header Parsing

First of all the [Accept Header specification](https://tools.ietf.org/html/rfc7231#section-5.3.2) mentions that any media range has lower priority than the more specific ones, so `text/html` has higher precedence than `text/*` and `*/*` even at the same `q` (quality) value.

The order of the media types seem to be irrelevant and in case of ties the server could return any of the requested media ranges.

## Our Troubles

As evidenced by [hanami/controller#225](https://github.com/hanami/controller/issues/225) something seems broken. At first I thought that this line of code was the problem: 

```ruby
if req_mime == DEFAULT_ACCEPT
  # See https://github.com/hanami/controller/issues/167
  match = default_content_type
else
```

What this does is: if the mime type being checked is `*/*`  we should return the configured default content type (`text/html` in hanami's case, `application/octet-stream` on controller' s).

That led me to this part of the code:

```ruby
values = ::Rack::Utils.q_values(q_value_header)
values = values.map do |req_mime, quality|
  if req_mime == DEFAULT_ACCEPT
    # See https://github.com/hanami/controller/issues/167
    match = default_content_type
  else
    match = available_mimes.find { |am| ::Rack::Mime.match?(am, req_mime) }
  end
  next unless match
  [match, quality]
end.compact
```

Here's the bigger picture and what pointed me to even bigger problems. `Rack::Mime.match?` tries to *expand* the media ranges, so it will try to match `text/*` to `text/plain` for example.

The method from where this was taken has the following signature: `best_q_match(req_mimes, available_mimes)`. If we call it with a `req_mimes` of `application/json,text/html,*/*,text/*` what this snippet will output is: `[['application/json', 1.0], ['text/html', 1.0], ['text/html', 1.0], ['text/plain', 1.0]]`.

Then we proceed to sort this matrix using a custom sorting algorithm (same code is found on `rack 2.0`):

```ruby
 value = values.sort_by do |match, quality|
   (match.split('/'.freeze, 2).count('*'.freeze) * -10) + quality
 end.last
```

By then, no media ranges reach this part of the code, so the priority rule never gets applied. So we end up with `text/plain` when we should have returned either `text/html` or `application/json`.

### Differences when the Action has an `accept :json`

With the same `req_mime` as before and an `available_mimes` of `application/json` (the side effect of sending `Action.accept`) the result would be `text/html`. Why? Because the check for the `DEFAULT_ACCEPT` ignores the `available_mimes`, it ends up in the result, gets sorted and picked in the end. 

## Solution

I borrowed a lot of ideas on how to solve it by looking at [negotiator](https://github.com/jshttp/negotiator) and seeing how the python, nodejs communities (among others) solved this.

I created an object (name `Specification` which is a crappy name, so I'm open to suggestions) that encapsulates the mime specification, its quality, index on the accepts header and the format solved by `Rack::Mime.match`.

Said object then calculates the priority and in case of ties opts for the type nearest to the start of the header.

Fixes #225

### CODE REVIEW

**Comment by mereghost** [comment]
Some benchs:

Memory Allocation between `Rack` and `Action::Mime` `best_q_match`, when called with `'application/json,text/html,audio/*;q=0.8,text/css;q=0.3,*/*'` and `Hanami::Mimes::MIME_TYPES.values`
```
Comparison:
              Hanami:      17544 allocated
                Rack:      18480 allocated - 1.05x more
```

And some speed:
```
Comparison:
                Rack:    18312.6 i/s
              Hanami:    17634.0 i/s - same-ish: difference falls within error
```

File: lib/hanami/action/mime.rb [hunk 1]
```diff
@@ -565,33 +560,41 @@ def content_type_with_charset
...
 
-        value.first if value
+        attr_reader :quality, :index, :mime, :format, :priority
+        def initialize(mime, quality, index, format = mime)
+          @quality, @index, @format = quality, index, format
+          calculate_priority(mime)
+        end
+
+        def <=>(other)
+          return priority <=> other.priority unless priority == other.priority
```
Comment (TiteiKo) [inline lib/hanami/action/mime.rb]: I'm guessing you don't compare quality here because it's already taken into account in the priority formula?

File: lib/hanami/action/mime.rb [hunk 2]
```diff
@@ -565,33 +560,41 @@ def content_type_with_charset
...
         end
 
-        value = values.sort_by do |match, quality|
-          (match.split('/'.freeze, 2).count('*'.freeze) * -10) + quality
-        end.last
+        value = values.max
+        value.format if value
+      end
+
+      class Specification
```
Comment (TiteiKo) [inline lib/hanami/action/mime.rb]: `RequestMimeWeight`?

File: lib/hanami/action/mime.rb [hunk 3]
```diff
@@ -565,33 +560,41 @@ def content_type_with_charset
...
-        values = ::Rack::Utils.q_values(q_value_header)
-        values = values.map do |req_mime, quality|
-          if req_mime == DEFAULT_ACCEPT
-            # See https://github.com/hanami/controller/issues/167
-            match = default_content_type
-          else
-            match = available_mimes.find { |am| ::Rack::Mime.match?(am, req_mime) }
-          end
+        values = []
+        ::Rack::Utils.q_values(q_value_header).each_with_index do |(req_mime, quality), index|
```
Comment (TiteiKo) [inline lib/hanami/action/mime.rb]: You could make your code a bit more elegant:

```ruby
     def best_q_match(q_value_header, available_mimes)
        values = ::Rack::Utils.q_values(q_value_header).each_with_index.map do |(req_mime, quality), index|
          match = available_mimes.find { |am| ::Rack::Mime.match?(am, req_mime) }
          Specification.new(req_mime, quality, index, match) if match
        end

        values.compact.max&.format
      end
```

Comment (mereghost) [inline lib/hanami/action/mime.rb]: Gah! I keep forgetting I can chain `Enumerator` calls. Shame on me for still having some ruby1.8 reflexes. 

That would leave the atribution to values a moot point and I could chain the `compact.max&.format` to the end of the block. WDYT?

File: lib/hanami/action/mime.rb (hunk 2 above)
Comment (mereghost) [inline lib/hanami/action/mime.rb]: I'm really bad at naming things, so naturally your suggestion seems better. :D

File: lib/hanami/action/mime.rb (hunk 1 above)
Comment (mereghost) [inline lib/hanami/action/mime.rb]: Yep.

Since priority already factors the quality of the mime type, there's no need to compare based into it. TBH I starting by comparing it, ran some tests, got weird results and then realized that.

Oh, and thanks for the review @TiteiKo =)

File: lib/hanami/action/mime.rb (hunk 3 above)
Comment (TiteiKo) [inline lib/hanami/action/mime.rb]: Yes `values` is useless, I've let it on another line for readability but hesitated, so if you find it understandable enough, just chain to the end :+1:

File: lib/hanami/action/mime.rb [hunk 4]
```diff
@@ -565,33 +560,41 @@ def content_type_with_charset
...
+        attr_reader :quality, :index, :mime, :format, :priority
+        def initialize(mime, quality, index, format = mime)
+          @quality, @index, @format = quality, index, format
+          calculate_priority(mime)
+        end
+
+        def <=>(other)
+          return priority <=> other.priority unless priority == other.priority
+          other.index <=> index
+          # return other.quality <=> quality unless quality == other.quality
```
Comment (TiteiKo) [inline lib/hanami/action/mime.rb]: :ghost:

File: lib/hanami/action/mime.rb [hunk 5]
```diff
@@ -565,33 +560,37 @@ def content_type_with_charset
...
+          calculate_priority(mime)
         end
 
-        value = values.sort_by do |match, quality|
-          (match.split('/'.freeze, 2).count('*'.freeze) * -10) + quality
-        end.last
+        def <=>(other)
+          return priority <=> other.priority unless priority == other.priority
+          other.index <=> index
+          # return other.quality <=> quality unless quality == other.quality
```
Comment (TiteiKo) [inline lib/hanami/action/mime.rb]: Please remove this commented code :ghost:

Comment (mereghost) [inline lib/hanami/action/mime.rb]: /facepalm
