### PR TITLE
Keep flash after redirect

### LINKED ISSUE #213: Regression: flash after redirect broken
Flash messages should survive after a redirect. They used to with `0.9.2`, but now they don't, with `1.0.0.beta1`. 

This is a result from #202. Specifically, [the change to the implementation of `_values` in `lib/hanami/action/flash.rb`](https://github.com/hanami/controller/pull/202/files#diff-ce13f23d4ed57d06a91f48c61b42c054L145). I reverted that one line locally and flashes survive redirects.

Note: that line should not just be reverted, since we should still address #196.

Discovered in parallel (and simultaneously!) by @deangerber. I think someone else mentioned this recently too, but I can't find who it was.

### PR DESCRIPTION
**Pull request by jodosha**
Closes #213

### CODE REVIEW

**Comment by jodosha** [comment]
@cllns Please review, I updated the tests according to the strategy that we just discussed about.

File: test/integration/full_stack_test.rb [hunk 1]
```diff
@@ -52,11 +52,11 @@ def app
     post '/settings', {}
     follow_redirect!
 
-    last_response.headers['X-Flash'].must_equal 'Saved!'
+    last_response.body.must_match %r{Hanami::Action::Flash:0x[\d\w]* {:message=>"Saved!"}}
```
Comment (cllns) [inline test/integration/full_stack_test.rb]: I think we can do `\h{12}` instead of `[\d\w]*` ? or at least `\h+`

File: test/integration/full_stack_test.rb [hunk 2]
```diff
@@ -52,11 +52,11 @@ def app
...
 
     get '/settings'
 
-    last_response.headers['X-Flash'].must_equal "Blank message"
+    last_response.body.must_match %r{Hanami::Action::Flash:0x[\d\w]* {}}
```
Comment (cllns) [inline test/integration/full_stack_test.rb]: same as above

**Comment by jodosha** [comment]
This number depends on the architecture where the Ruby VM is running on. I prefer a relaxed regexp, cause it isn't too much important here.

http://lucaguidi.com

**Comment by cllns** [comment]
hm, I see :) well `\w` contains `\d` (unless that's not true on some platforms too 😝 )

**Comment by AlfonsoUceda** [comment]
👍

**Comment by jodosha** [comment]
@cllns 
> hm, I see :) well \w contains \d (unless that's not true on some platforms too 😝 )

It's about the length of the string, rather than the contents.
